apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: infra-project
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io/
    targetRevision: 1.9.1
    helm:
      releaseName: cert-manager
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
