apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  destination:
    namespace: home-stuff
    server: https://kubernetes.default.svc
  project: home-stuff
  source:
    chart: plex
    repoURL: https://charts.truecharts.org
    targetRevision: 10.2.12
    helm:
      releaseName: plex
        #values: |
        #  installCRDs: true
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
