apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
spec:
  destination:
    namespace: home-stuff
    server: https://kubernetes.default.svc
  project: home-stuff
  source:
    chart: radarr
    repoURL: https://charts.truecharts.org
    targetRevision: 11.0.37
    helm:
      releaseName: radarr
        #values: |
        #  installCRDs: true
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
